import { shuffle } from './random.js';

export function makeRound({ players, passOrder, category, word, impostorCount, settings, impostors, yesNoQuestion = '' }) {
  return {
    settings,
    passOrder: passOrder || (settings.randomisePassOrder ? shuffle(players) : [...players]),
    category,
    word,
    impostors: impostors || new Set(shuffle(players).slice(0, impostorCount)),
    revealIndex: 0,
    revealedPlayers: [],
    clueRound: 1,
    cluePlayerIndex: 0,
    clues: [],
    votes: {},
    skipVotes: {},
    yesNoQuestion,
    yesNoAnswers: {},
    bonusCandidates: [],
    bonusReason: '',
    bonusDuelClues: {},
    bonusVotes: {},
    bonusWinner: null,
    bonusTieSource: null,
    hotSeatPlayer: null,
    hotSeatFinalClue: '',
    hotSeatVotes: {},
    hotSeatAccepted: null,
    hotSeatUsed: false,
    hotSeatRevoteVotes: {},
    eliminatedPlayer: null,
    resultReason: '',
    impostorGuess: '',
    outcome: null,
  };
}
