export const GAME_MODES = {
  classic: {
    id: 'classic',
    name: 'Classic',
    badge: 'Original',
    minPlayers: 3,
    defaultImpostors: 1,
    maxImpostors: 3,
    normalRole: 'MOB',
    impostorRole: 'Impostor',
    title: 'One word. One snake.',
    description: 'Most players know the secret word. Impostors only know the category and must survive the vote.',
    clueTitle: 'One clue each. No repeats. No obvious giveaways.',
    guessLabel: 'Guess the secret word to steal the win.',
  },
  tVirus: {
    id: 'tVirus',
    name: 'T‑Virus',
    badge: 'Infection',
    minPlayers: 4,
    defaultImpostors: 1,
    maxImpostors: 2,
    normalRole: 'Survivor',
    impostorRole: 'Infected',
    title: 'The infection is inside the MOB.',
    description: 'Survivors know the cure word. Infected players know only the category and must blend in.',
    clueTitle: 'The virus spreads through weak clues. Keep it sharp.',
    guessLabel: 'Guess the cure word to infect the whole MOB.',
  },
  doubleAgent: {
    id: 'doubleAgent',
    name: 'Double Agent',
    badge: '2+ snakes',
    minPlayers: 5,
    defaultImpostors: 2,
    maxImpostors: 3,
    normalRole: 'MOB',
    impostorRole: 'Double Agent',
    title: 'Two snakes. One table.',
    description: 'Classic rules, but with more impostors. Best for bigger groups and louder debates.',
    clueTitle: 'Watch for copied clues and coordinated lies.',
    guessLabel: 'One agent can guess the secret word to steal the win.',
  },
  hardcore: {
    id: 'hardcore',
    name: 'Hardcore',
    badge: 'Fast',
    minPlayers: 3,
    defaultImpostors: 1,
    maxImpostors: 2,
    normalRole: 'MOB',
    impostorRole: 'Impostor',
    title: 'Less room to hide.',
    description: 'Short clues, faster vote, and fewer chances for the impostor to recover.',
    clueTitle: 'One short clue only. No waffle.',
    guessLabel: 'One quick guess. No second chance.',
  },
  spyfall: {
    id: 'spyfall',
    name: 'Spyfall',
    badge: 'Questions',
    minPlayers: 4,
    defaultImpostors: 1,
    maxImpostors: 2,
    normalRole: 'Agent',
    impostorRole: 'Spy',
    title: 'Everyone knows the place except the spy.',
    description: 'Agents know the location. The spy sees only the category and tries to guess the location.',
    clueTitle: 'Ask questions. Answer naturally, but do not reveal the location.',
    guessLabel: 'Guess the location to win as the spy.',
  },
  wereword: {
    id: 'wereword',
    name: 'Wereword',
    badge: 'Hidden roles',
    minPlayers: 4,
    defaultImpostors: 1,
    maxImpostors: 2,
    normalRole: 'Villager',
    impostorRole: 'Werewolf',
    title: 'Find the magic word or expose the wolf.',
    description: 'Villagers know the goal. Werewolves mislead the group. Use timed guess rounds before voting.',
    clueTitle: 'Ask questions and build towards the word before the vote.',
    guessLabel: 'Guess the magic word before the final vote.',
  },
};

export const MODE_IDS = Object.keys(GAME_MODES);

export const DEFAULT_SETTINGS = {
  guessRounds: 1,
  clueRounds: 1,
  discussionSeconds: 60,
  showCategoryToImpostor: true,
  allowImpostorFinalGuess: true,
  randomisePassOrder: false,
  revealVotesAfterRound: true,
  pointsMobWin: 1,
  pointsImpostorWin: 2,
};

export const SESSION_PRESETS = {
  casual: {
    name: 'Casual',
    description: 'Good default for quick phone sessions.',
    settings: { guessRounds: 1, clueRounds: 1, discussionSeconds: 60, allowImpostorFinalGuess: true },
  },
  chaos: {
    name: 'Chaos',
    description: 'More clues, more guess attempts, more arguments.',
    settings: { guessRounds: 2, clueRounds: 2, discussionSeconds: 120, allowImpostorFinalGuess: true },
  },
  quickfire: {
    name: 'Quickfire',
    description: 'Fast rounds before someone overthinks it.',
    settings: { guessRounds: 0, clueRounds: 1, discussionSeconds: 30, allowImpostorFinalGuess: false },
  },
  interrogation: {
    name: 'Interrogation',
    description: 'Best for Spyfall/Wereword-style question rounds.',
    settings: { guessRounds: 2, clueRounds: 3, discussionSeconds: 180, allowImpostorFinalGuess: true },
  },
};
