export const WORD_BANK = {
  'Public Places': [
    'Embassy',
    'Courthouse',
    'Observatory',
    'Auction House',
    'Opera House',
    'Harbour',
    'Lighthouse',
    'Train Platform',
    'Casino Floor',
    'University Library',
    'Hotel Lobby',
    'Emergency Room',
    'Recording Studio',
    'Rooftop Bar',
    'Underground Station',
    'Museum Archive',
    'Airport Lounge',
    'Conference Hall',
    'Backstage Area',
    'Wine Cellar',
    'Botanical Garden',
    'Control Tower',
    'Theatre Balcony',
    'Private Club',
  ],

  'Situations': [
    'First Date',
    'Job Interview',
    'Family Dinner',
    'Power Cut',
    'Missed Flight',
    'Surprise Party',
    'Flat Tyre',
    'Wedding Speech',
    'Exam Day',
    'Awkward Silence',
    'Last-Minute Plan',
    'Secret Meeting',
    'Lost Wallet',
    'Group Holiday',
    'Rain Delay',
    'Late Arrival',
    'Bad Haircut',
    'Wrong Address',
    'Double Booking',
    'Unexpected Guest',
    'Broken Phone',
    'Fake Excuse',
    'Parking Fine',
    'Rumour Spreading',
  ],

  'Emotions & Vibes': [
    'Suspicion',
    'Relief',
    'Jealousy',
    'Confidence',
    'Embarrassment',
    'Nostalgia',
    'Panic',
    'Awkwardness',
    'Temptation',
    'Regret',
    'Excitement',
    'Disappointment',
    'Tension',
    'Pride',
    'Confusion',
    'Guilt',
    'Curiosity',
    'Boredom',
    'Revenge',
    'Trust',
    'Pressure',
    'Doubt',
    'Hope',
    'Paranoia',
  ],

  'Actions': [
    'Negotiating',
    'Bluffing',
    'Sneaking',
    'Celebrating',
    'Apologising',
    'Investigating',
    'Pretending',
    'Escaping',
    'Overthinking',
    'Interrupting',
    'Whispering',
    'Bargaining',
    'Flirting',
    'Complaining',
    'Showing Off',
    'Avoiding',
    'Explaining',
    'Hiding',
    'Spying',
    'Lying',
    'Defending',
    'Confessing',
    'Risking',
    'Celebrating Too Early',
  ],

  'Mystery Objects': [
    'Envelope',
    'Receipt',
    'Keycard',
    'Old Photograph',
    'Locked Box',
    'Fake Passport',
    'Burner Phone',
    'Map',
    'Gold Ring',
    'USB Stick',
    'Briefcase',
    'Mask',
    'Ticket Stub',
    'Diary',
    'Hidden Camera',
    'Chess Piece',
    'Candle',
    'Compass',
    'Broken Watch',
    'Signature',
    'Code Word',
    'Hotel Key',
    'Missing Page',
    'Black Glove',
  ],

  'Characters': [
    'Detective',
    'Bodyguard',
    'Celebrity',
    'Neighbour',
    'Tourist',
    'Referee',
    'Bouncer',
    'Magician',
    'Lawyer',
    'Journalist',
    'Chef',
    'Mechanic',
    'Pilot',
    'Lifeguard',
    'Professor',
    'Taxi Driver',
    'Security Guard',
    'Influencer',
    'Waiter',
    'Doctor',
    'Translator',
    'Host',
    'Rival',
    'Witness',
  ],

  'Media & Culture': [
    'Plot Twist',
    'Villain Arc',
    'Opening Scene',
    'Final Episode',
    'Soundtrack',
    'Spoiler',
    'Red Carpet',
    'Reality Show',
    'Documentary',
    'Trailer',
    'Oscar Speech',
    'Deleted Scene',
    'Cult Classic',
    'Cliffhanger',
    'Box Office',
    'Remake',
    'Cameo',
    'Season Finale',
    'Fan Theory',
    'Behind The Scenes',
    'Bad Review',
    'Plot Hole',
    'Main Character',
    'Antihero',
  ],

  'Sports & Competition': [
    'Penalty Shootout',
    'Derby Day',
    'VAR Check',
    'Transfer Rumour',
    'Underdog Win',
    'Team Captain',
    'Changing Room',
    'Press Conference',
    'Injury Time',
    'Home Advantage',
    'Red Card',
    'Comeback',
    'Title Race',
    'Friendly Match',
    'Training Ground',
    'Away Fans',
    'Trophy Lift',
    'Last-Minute Winner',
    'Referee Mistake',
    'Goal Celebration',
    'Mind Games',
    'Rival Club',
    'Clean Sheet',
    'Match Fixing',
  ],

  'Food & Drink': [
    'Tasting Menu',
    'Midnight Snack',
    'Street Food',
    'Burnt Toast',
    'Secret Recipe',
    'Room Service',
    'Energy Drink',
    'Birthday Cake',
    'Leftovers',
    'Spicy Sauce',
    'Breakfast Buffet',
    'Food Poisoning',
    'Fancy Restaurant',
    'Takeaway Order',
    'Coffee Break',
    'Picnic Basket',
    'Kitchen Disaster',
    'Wedding Cake',
    'Wine Tasting',
    'Comfort Food',
    'Late-Night Kebab',
    'Chef Special',
    'Table Reservation',
    'Secret Ingredient',
  ],

  'Travel & Holiday': [
    'Passport Control',
    'Lost Luggage',
    'Hotel Upgrade',
    'Tour Guide',
    'City Break',
    'Road Trip',
    'Delayed Flight',
    'Beach Resort',
    'Ski Lodge',
    'Camping Trip',
    'Cruise Ship',
    'Travel Insurance',
    'Souvenir Shop',
    'Wrong Train',
    'Border Crossing',
    'Airport Security',
    'Rental Car',
    'Local Market',
    'Sunburn',
    'Tourist Trap',
    'Mountain Cabin',
    'All-Inclusive',
    'Hidden Beach',
    'Language Barrier',
  ],

  'Technology': [
    'Group Chat',
    'Voice Note',
    'Deleted Message',
    'Low Battery',
    'Face ID',
    'Wi-Fi Password',
    'Fake Profile',
    'Online Status',
    'Screen Recording',
    'Private Browser',
    'Video Call',
    'Algorithm',
    'Password Reset',
    'Autocorrect',
    'Cloud Backup',
    'Notification',
    'Spam Email',
    'Location Sharing',
    'AirDrop',
    'Search History',
    'Read Receipt',
    'Blocked Contact',
    'Two-Factor Code',
    'Glitch',
  ],

  'Abstract Concepts': [
    'Reputation',
    'Luck',
    'Power',
    'Loyalty',
    'Betrayal',
    'Freedom',
    'Justice',
    'Chaos',
    'Routine',
    'Ambition',
    'Tradition',
    'Risk',
    'Strategy',
    'Control',
    'Influence',
    'Timing',
    'Pressure',
    'Trust',
    'Sacrifice',
    'Respect',
    'Discipline',
    'Temptation',
    'Patience',
    'Revenge',
  ],
};

export const CATEGORY_NAMES = Object.keys(WORD_BANK);
