export const WORD_BANK = {
  'A$AP MOB': [
    'Pro Clubs',
    'Mob Coins',
    'Chappie',
    'Away Day',
    'The Dressing Room',
    'Club Captain',
    'Last Minute Winner',
    'Team Sheet',
    'Golden Crest',
    'Weekend Session',
  ],
  Football: [
    'Penalty',
    'Goalkeeper',
    'Striker',
    'Corner Kick',
    'Red Card',
    'Derby',
    'Free Kick',
    'Clean Sheet',
    'Hat Trick',
    'Offside',
    'Tackle',
    'VAR',
  ],
  Gaming: [
    'Controller',
    'Lobby',
    'Boss Fight',
    'Headshot',
    'Loot Box',
    'Respawn',
    'Ranked Match',
    'Spawn Point',
    'Patch Notes',
    'Final Boss',
  ],
  Food: [
    'Pizza',
    'Burger',
    'Kebab',
    'Sushi',
    'Tacos',
    'Curry',
    'Pancakes',
    'Chicken Wings',
    'Noodles',
    'Steak',
  ],
  Places: [
    'Airport',
    'Gym',
    'Pub',
    'Cinema',
    'Beach',
    'Hospital',
    'School',
    'Hotel',
    'Train Station',
    'Stadium',
  ],
  Movies: [
    'Batman',
    'Shrek',
    'Titanic',
    'Avengers',
    'Joker',
    'Fast & Furious',
    'Spider-Man',
    'Toy Story',
    'John Wick',
    'Harry Potter',
  ],
  Objects: [
    'Wallet',
    'Phone',
    'Keys',
    'Backpack',
    'Sunglasses',
    'Watch',
    'Headphones',
    'Bottle',
    'Remote',
    'Laptop',
  ],
  Animals: [
    'Dog',
    'Cat',
    'Shark',
    'Eagle',
    'Snake',
    'Horse',
    'Lion',
    'Monkey',
    'Wolf',
    'Crocodile',
  ],
};

export const CATEGORY_NAMES = Object.keys(WORD_BANK);
